### ISSUE TITLE
NewRelic Transactions does not shows the route path

### ISSUE THREAD

**Issue by mohamed0123** [newrelic-experimental/newrelic-java-quarkus#4]
I start by downloading the most recent source, building the project, gathering all created jars, and placing them in the extensions folder inside the NewRelic path that contains the NewRelic jar.

But there are no routes as listed below only shows HTTP Method.
![Capture](https://user-images.githubusercontent.com/17961077/213476211-2c469f17-6231-44f8-ad52-09209fc111e1.PNG)

Note 
I am trying to monitor [keycloak](https://www.keycloak.org/) application.

**Comment by gsidhwani-nr** [comment]
Fixed in version [2.1.1](https://github.com/newrelic-experimental/newrelic-java-quarkus/releases/tag/v2.1.1)

The route path is not displayed in Transaction name. Please test and share your feedback. 

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/a9dd5457-6b00-45da-b23a-61f6151bdb3a">
